"""deleted businesscreate

Revision ID: 548b2ddbe4ff
Revises: 13ae45adb1f6
Create Date: 2025-05-24 12:52:03.251942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '548b2ddbe4ff'
down_revision: Union[str, None] = '13ae45adb1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
