"""added otp

Revision ID: 8791c5294e05
Revises: f12e7f430e42
Create Date: 2025-06-12 04:48:29.933119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '8791c5294e05'
down_revision: Union[str, None] = 'f12e7f430e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_expiry')
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###
