"""edited user table

Revision ID: 92455f7b5c46
Revises: d70cb40fd105
Create Date: 2025-06-06 16:40:51.322890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92455f7b5c46'
down_revision: Union[str, None] = 'd70cb40fd105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_business_email', table_name='user')
    op.drop_column('user', 'business_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_email', sa.VARCHAR(), nullable=True))
    op.create_index('ix_user_business_email', 'user', ['business_email'], unique=1)
    # ### end Alembic commands ###
