"""update the models

Revision ID: f40b47b1651d
Revises: 9e30a0917957
Create Date: 2025-06-06 16:06:43.133225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f40b47b1651d"
down_revision: Union[str, None] = "9e30a0917957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column("user", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
